import { useEffect, useState } from "react"
import Head from "next/head"

import styles from "../styles/Home.module.css"
import Appbar from "../components/appbar"
import List from "@mui/material/List"
import ListItem from "@mui/material/ListItem"
import ListItemText from "@mui/material/ListItemText"
import ListItemAvatar from "@mui/material/ListItemAvatar"
import Avatar from "@mui/material/Avatar"
import Dialog, { DialogProps } from "@mui/material/Dialog"
import ListItemButton from "@mui/material/ListItemButton"
import Card from "@mui/material/Card"
import CardContent from "@mui/material/CardContent"
import { CardActionArea } from "@mui/material"
import Typography from "@mui/material/Typography"

import axios from "axios"

export default function Home() {
  const [getListPatient, setListPatient] = useState({ data: [] })
  const [isOpenDialog, setOpenDialog] = useState(false)
  const [fullWidth, setFullWidth] = useState(true)

  const fetchData = async () => {
    const res = await axios.get("http://localhost:1337/api/patients")
    setListPatient(res.data)
  }
  const handleClickOpen = () => {
    setOpenDialog(true)
  }

  const handleClose = () => {
    setOpenDialog(false)
  }
  useEffect(() => {
    fetchData()
  }, [])
  return (
    <div className={styles.container}>
      <Appbar />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dialog open={isOpenDialog} onClose={handleClose}>
        <Card>
          <CardActionArea>
            <CardContent>
              <Typography gutterBottom variant="h5" component="div">
                Lizard
              </Typography>
              <Typography variant="body2" color="text.secondary">
                Lizards are a widespread group of squamate reptiles, with over
                6,000 species, ranging across all continents except Antarctica
              </Typography>
            </CardContent>
          </CardActionArea>
        </Card>
      </Dialog>
      <main className={styles.main}>
        <List
          sx={{ width: "100%", maxWidth: 360, bgcolor: "background.paper" }}
        >
          {getListPatient.data.map((item) => {
            return (
              <ListItem key={item.toString()}>
                <ListItemButton onClick={handleClickOpen}>
                  <ListItemAvatar>
                    <Avatar>
                      <Avatar>{item.attributes.name.slice(0, 1)}</Avatar>
                    </Avatar>
                  </ListItemAvatar>
                  <ListItemText>{item.attributes.name}</ListItemText>
                </ListItemButton>
              </ListItem>
            )
          })}
        </List>
      </main>
    </div>
  )
}
